In [ ]:
## NUMPY LIBRARY

# 0- 
# 1-
# 2-
# 3- 
# 4- 

In [ ]:
## NUMPY LIBRARY - It is used for scientific computing. It provide support for arrays and matrices, along with a collection of
#                  mathematical functions to operate on these data structures

In [ ]:
!pip install numpy                          

  Using cached numpy-2.1.3-cp312-cp312-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.1.3-cp312-cp312-win_amd64.whl (12.6 MB)


In [ ]:
## IMPORTING NUMPY

import numpy as np

# One dimension Array

arr1 = np.array([1,2,3,4,5])
print(type(arr1))
print(arr1.shape)                   

<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)                           # We identify dimensions by brackets

array([[1, 2, 3, 4, 5]])

In [ ]:
arr2 = np.array([[1,2,3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


In [9]:
# Two dimension Array

arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2.shape)

(2, 5)


In [ ]:
## IN_BUILT FUNTIONS/ATTRIBUTES IN NUMPY

np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))                      # (rows,columns)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((2,4))                     # (rows,columns)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Identity Matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])

print("Array: \n", arr)
print("Shape:",arr.shape)
print("Number of Dimensions:",arr.ndim)
print("Size of Array:",arr.size)
print("Data Type:",arr.dtype)
print("Item Size (in Bytes):",arr.itemsize)

Array: 
 [[1 2 3 4 5]
 [6 7 8 9 0]]
Shape: (2, 5)
Number of Dimensions: 2
Size of Array: 10
Data Type: int64
Item Size (in Bytes): 8


In [ ]:
## VECTORIZED OPERATIONS

arr1 = np.array([1,2,3,4,5,6])                      # Numpy automatically perform operations on index basis
arr2 = np.array([11,12,13,14,15,16])

# Addition
print("Addition: ", arr1+arr2)

# Substraction
print("Substraction: ", arr1-arr2)

# Multiplication
print("Multiplication: ", arr1*arr2)

# Division
print("Division: ", arr1/arr2)

Addition:  [12 14 16 18 20 22]
Substraction:  [-10 -10 -10 -10 -10 -10]
Multiplication:  [11 24 39 56 75 96]
Division:  [0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375     ]


In [33]:
## UNIVERSAL FUNCTIONS

arr = np.array([1,2,3,4,5,6])

# Square Root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural Log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
## SLICING ON ARRAYS

arr = np.array([

    [1,2,3,4],
    [5,6,7,8],
    [10,11,12,14]
])

print("ARRAY: \n",arr)

ARRAY: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 14]]


In [39]:
print(arr[0:1])
print(arr[1:2,1:3])

[[1 2 3 4]]
[[6 7]]


In [40]:
## MODYFYING ARRAY

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [ 10  11  12  14]]


In [41]:
arr[1:]=99
print(arr)

[[100   2   3   4]
 [ 99  99  99  99]
 [ 99  99  99  99]]


In [46]:
## STATISTICAL CONCEPTS - NORMALIZATION

array = [1,2,3,4,5,6,7,8,9,10]

# Mean 
mean = np.mean(array)
print("Mean",mean)

# Mean 
median = np.median(array)
print("Median",median)

# Standard Deviation 
std_dev = np.std(array)
print("Standard Deviation",std_dev)

# Variance 
variance = np.var(array)
print("Variance",variance)



Mean 5.5
Median 5.5
Standard Deviation 2.8722813232690143
Variance 8.25


In [48]:
## LOGICAL OPERATIONS

data = np.array([1,2,3,4,5,6,7,8,9])

data[data>3]

array([4, 5, 6, 7, 8, 9])